In [6]:
import pandas as pd

Leitura Excel

In [13]:
# O primeiro abrituto é o nome do arquivo e o segundo é o nome da planilha/aba/pasta
# Você pode conferir o nome da planilha olhando no canto inferior esquerdo ao abrir o excel
pd.read_excel("notas.xlsx", sheet_name="Sheet1")

    Aluno  Prova  Projeto  Seminário
0    Joao      8        6         10
1   Maria      7        7          9
2  Victor      9        8          8
3   Joyce     10        9          7
4  Felipe      6       10          6

Leitura de páginas da internet

In [22]:
# para fazer leitura de uma página da web, o primeiro passo é importar a blibioteca request
import requests
url = "https://www.worldcoinindex.com"
# Usando a função get e passando o site adquirimos uma resposta, que contém HTML do site
resposta = requests.get(url)
resposta

In [23]:
# podemos usar a função do pandas rad para ler o conteudo HTML de dentro da respostas
leitura_html = pd.read_html(resposta.text)
leitura_html

[       # Unnamed: 1          Name Ticker  Last price        %     24 high  \
 0      1        NaN       Bitcoin    BTC    $ 67,202   -0.51%    $ 68,505
 1      2        NaN      Ethereum    ETH  $ 4,746.37   -1.36%  $ 4,840.23
 2      3        NaN       Cardano    ADA      $ 2.30   +8.22%      $ 2.37
 3      4        NaN      Loopring    LRC      $ 2.84  +39.03%      $ 3.01
 4      5        NaN      Litecoin    LTC    $ 266.72  +16.51%    $ 274.16
 ..   ...        ...           ...    ...         ...      ...         ...
 97    96        NaN          Coti   COTI  $ 0.576574   +2.15%  $ 0.585905
 98    97        NaN    Ltonetwork    LTO  $ 0.386475  +22.72%  $ 0.451545
 99    98        NaN           Nem    XEM  $ 0.206941   +0.95%  $ 0.209610
 100   99        NaN     Thorchain   RUNE     $ 13.00   -5.38%     $ 13.74
 101  100        NaN  KuCoin Token    KCS     $ 23.28   -0.91%     $ 25.01

          24 low Price Charts 7d 24 volume  # Coins Market cap
 0      $ 66,369             NaN  $ 17.28B   18.86M    $ 1.26T
 1    $ 4,717.63             NaN  $ 10.85B  118.27M  $ 561.38B
 2        $ 2.11             NaN   $ 5.34B   31.94B   $ 73.51B
 3        $ 2.01             NaN   $ 4.96B    1.32B    $ 3.74B
 4      $ 227.22             NaN   $ 4.86B   67.40M   $ 17.97B
 ..          ...             ...       ...      ...        ...
 97   $ 0.541102             NaN  $ 98.15M  868.67M  $ 500.85M
 98   $ 0.310231             NaN  $ 96.85M  280.84M  $ 108.53M
 99   $ 0.200919             NaN  $ 94.11M    8.99B    $ 1.86B
 100     $ 12.68             NaN  $ 94.03M  265.17M    $ 3.44B
 101     $ 22.22             NaN  $ 92.91M   91.04M    $ 2.11B

 [102 rows x 12 columns]]

# O resultado da leitura é incerto, então é sempre interessante verificar o tipo dessa leitura

In [31]:
print("Tipo = ", type(leitura_html))
# neste caso, é uma lista

Tipo =  <class 'list'>

In [33]:
# neste caso, é uma lista com um elemento só
print("tamanho =", len(leitura_html))

tamanho = 1

In [34]:
# Então vamos verificar o tipo desse elemento
print("TipoDoElemento =", type(leitura_html[0]))
# é um dataframe

TipoDoElemento = <class 'pandas.core.frame.DataFrame'>

In [29]:
tabela = leitura_html[0]
tabela

,#,Unnamed: 1,Name,Ticker,Last price,%,24 high,24 low,Price Charts 7d,24 volume,# Coins,Market cap
0,1,NaN,Bitcoin,BTC,"$ 67,202",-0.51%,"$ 68,505","$ 66,369",NaN,$ 17.28B,18.86M,$ 1.26T
1,2,NaN,Ethereum,ETH,"$ 4,746.37",-1.36%,"$ 4,840.23","$ 4,717.63",NaN,$ 10.85B,118.27M,$ 561.38B
2,3,NaN,Cardano,ADA,$ 2.30,+8.22%,$ 2.37,$ 2.11,NaN,$ 5.34B,31.94B,$ 73.51B
3,4,NaN,Loopring,LRC,$ 2.84,+39.03%,$ 3.01,$ 2.01,NaN,$ 4.96B,1.32B,$ 3.74B
4,5,NaN,Litecoin,LTC,$ 266.72,+16.51%,$ 274.16,$ 227.22,NaN,$ 4.86B,67.40M,$ 17.97B
...,...,...,...,...,...,...,...,...,...,...,...,...
97,96,NaN,Coti,COTI,$ 0.576574,+2.15%,$ 0.585905,$ 0.541102,NaN,$ 98.15M,868.67M,$ 500.85M
98,97,NaN,Ltonetwork,LTO,$ 0.386475,+22.72%,$ 0.451545,$ 0.310231,NaN,$ 96.85M,280.84M,$ 108.53M
99,98,NaN,Nem,XEM,$ 0.206941,+0.95%,$ 0.209610,$ 0.200919,NaN,$ 94.11M,8.99B,$ 1.86B
100,99,NaN,Thorchain,RUNE,$ 13.00,-5.38%,$ 13.74,$ 12.68,NaN,$ 94.03M,265.17M,$ 3.44B
101,100,NaN,KuCoin Token,KCS,$ 23.28,-0.91%,$ 25.01,$ 22.22,NaN,$ 92.91M,91.04M,$ 2.11B

In [35]:
tabela.head()
# Mostra as 5 primeiras loinhas da tabela

,#,Unnamed: 1,Name,Ticker,Last price,%,24 high,24 low,Price Charts 7d,24 volume,# Coins,Market cap
0,1,NaN,Bitcoin,BTC,"$ 67,202",-0.51%,"$ 68,505","$ 66,369",NaN,$ 17.28B,18.86M,$ 1.26T
1,2,NaN,Ethereum,ETH,"$ 4,746.37",-1.36%,"$ 4,840.23","$ 4,717.63",NaN,$ 10.85B,118.27M,$ 561.38B
2,3,NaN,Cardano,ADA,$ 2.30,+8.22%,$ 2.37,$ 2.11,NaN,$ 5.34B,31.94B,$ 73.51B
3,4,NaN,Loopring,LRC,$ 2.84,+39.03%,$ 3.01,$ 2.01,NaN,$ 4.96B,1.32B,$ 3.74B
4,5,NaN,Litecoin,LTC,$ 266.72,+16.51%,$ 274.16,$ 227.22,NaN,$ 4.86B,67.40M,$ 17.97B

In [37]:
# para remover essas colunas usamos o loc
# No primeiro atributo dezemos que linhas queremos localizar, usamis : para todas
# No segundo dizemos que colunas. Nesse caso selecionamos da coluna Nome para frente
# colocariamos o : no final, caso desejassemos selecionar as primeiras colunas até nome
tabela = tabela.loc[:,"Name":]
tabela

,Name,Ticker,Last price,%,24 high,24 low,Price Charts 7d,24 volume,# Coins,Market cap
0,Bitcoin,BTC,"$ 67,202",-0.51%,"$ 68,505","$ 66,369",NaN,$ 17.28B,18.86M,$ 1.26T
1,Ethereum,ETH,"$ 4,746.37",-1.36%,"$ 4,840.23","$ 4,717.63",NaN,$ 10.85B,118.27M,$ 561.38B
2,Cardano,ADA,$ 2.30,+8.22%,$ 2.37,$ 2.11,NaN,$ 5.34B,31.94B,$ 73.51B
3,Loopring,LRC,$ 2.84,+39.03%,$ 3.01,$ 2.01,NaN,$ 4.96B,1.32B,$ 3.74B
4,Litecoin,LTC,$ 266.72,+16.51%,$ 274.16,$ 227.22,NaN,$ 4.86B,67.40M,$ 17.97B
...,...,...,...,...,...,...,...,...,...,...
97,Coti,COTI,$ 0.576574,+2.15%,$ 0.585905,$ 0.541102,NaN,$ 98.15M,868.67M,$ 500.85M
98,Ltonetwork,LTO,$ 0.386475,+22.72%,$ 0.451545,$ 0.310231,NaN,$ 96.85M,280.84M,$ 108.53M
99,Nem,XEM,$ 0.206941,+0.95%,$ 0.209610,$ 0.200919,NaN,$ 94.11M,8.99B,$ 1.86B
100,Thorchain,RUNE,$ 13.00,-5.38%,$ 13.74,$ 12.68,NaN,$ 94.03M,265.17M,$ 3.44B
101,KuCoin Token,KCS,$ 23.28,-0.91%,$ 25.01,$ 22.22,NaN,$ 92.91M,91.04M,$ 2.11B

In [38]:
# podemosusar a função dropna para remover dados faltantes
# A função recebe um parametro chamado axis.
# Quando esse parametro é igual a 0, significa que estamos buscando linhas com elementos vazios
# Quanto esse paramentro é igual 1, significa que estamos buscando colunas com elementos vazios
tabela.dropna(axis=1)

,Name,Ticker,Last price,%,24 high,24 low,24 volume
0,Bitcoin,BTC,"$ 67,202",-0.51%,"$ 68,505","$ 66,369",$ 17.28B
1,Ethereum,ETH,"$ 4,746.37",-1.36%,"$ 4,840.23","$ 4,717.63",$ 10.85B
2,Cardano,ADA,$ 2.30,+8.22%,$ 2.37,$ 2.11,$ 5.34B
3,Loopring,LRC,$ 2.84,+39.03%,$ 3.01,$ 2.01,$ 4.96B
4,Litecoin,LTC,$ 266.72,+16.51%,$ 274.16,$ 227.22,$ 4.86B
...,...,...,...,...,...,...,...
97,Coti,COTI,$ 0.576574,+2.15%,$ 0.585905,$ 0.541102,$ 98.15M
98,Ltonetwork,LTO,$ 0.386475,+22.72%,$ 0.451545,$ 0.310231,$ 96.85M
99,Nem,XEM,$ 0.206941,+0.95%,$ 0.209610,$ 0.200919,$ 94.11M
100,Thorchain,RUNE,$ 13.00,-5.38%,$ 13.74,$ 12.68,$ 94.03M
101,KuCoin Token,KCS,$ 23.28,-0.91%,$ 25.01,$ 22.22,$ 92.91M

# Leitura de csv

In [42]:
imoveis = pd.read_csv("imoveis.csv")
imoveis

,ultimaAtualizacaoCadastral,situacao,sequencialImovel,proprietarioPrincipal,natureza,inscricaoImobiliaria,enderecoImovelNomeLogradouro,enderecoImovelMunicipio,enderecoImovelEstado,enderecoImovelComplemento,...,aliquotaImposto,situacaoPavimentacao,distrito,setor,quadra,face,lote,sequencial,longitude,latitude
0,02/12/2015,Ativo,1031171,MUNICIPIO DO RECIFE,Territorial,1.1410.190.02.0025.0000-6,RUA PAULINO GOMES DE SOUZA Q-PRACA,RECIFE,PE,NaN,...,0.000,Parcialmente Pavimentado,1,1410,190,2,25,1031171,NaN,NaN
1,29/11/2015,Ativo,1032984,MUNICIPIO DO RECIFE,Territorial,1.1410.140.01.0730.0000-0,RUA DO FUTURO Q-AREA L-D,RECIFE,PE,NaN,...,0.030,Parcialmente Pavimentado,1,1410,140,1,730,1032984,-34.904747,-8.036815
2,29/11/2015,Ativo,1049160,MUNICIPIO DO RECIFE,Predial,1.1426.030.01.0170.0000-3,RUA DR JOAQUIM ARRUDA FALCAO,RECIFE,PE,NaN,...,0.000,Parcialmente Pavimentado,1,1426,30,1,170,1049160,-34.887555,-8.040748
3,29/11/2015,Ativo,1050834,MUNICIPIO DO RECIFE,Predial,1.1426.043.01.0379.0000-4,RUA SACADURA CABRAL,RECIFE,PE,NaN,...,0.000,Não Pavimentado,1,1426,43,1,379,1050834,NaN,NaN
4,29/11/2015,Ativo,1063391,MUNICIPIO DO RECIFE,Territorial,1.1445.155.02.0670.0000-4,RUA CEL VIRGILIO DE MEDEIROS Q-A L-12,RECIFE,PE,NaN,...,0.000,Parcialmente Pavimentado,1,1445,155,2,670,1063391,-34.876882,-8.044247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,29/11/2015,Ativo,7777400,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0319-2,RUA AMADOR BUENO,RECIFE,PE,APTO 306 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777400,-34.897103,-8.089021
3091,29/11/2015,Ativo,7777418,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0320-6,RUA AMADOR BUENO,RECIFE,PE,APTO 307 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777418,-34.897103,-8.089021
3092,29/11/2015,Ativo,7777426,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0321-4,RUA AMADOR BUENO,RECIFE,PE,APTO 308 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777426,-34.897103,-8.089021
3093,29/11/2015,Ativo,7780141,MUNICIPIO DO RECIFE,Territorial,4.1540.067.01.0010.0001-5,RUA EDEIA,RECIFE,PE,NaN,...,0.000,Parcialmente Pavimentado,4,1540,67,1,10,7780141,NaN,NaN
3094,28/11/2015,Ativo,7780249,MUNICIPIO DO RECIFE,Predial,2.1185.015.10.0357.0001-6,RUA PORTAO DO GELO,RECIFE,PE,NaN,...,0.000,Não Pavimentado,2,1185,15,10,357,7780249,NaN,NaN

In [44]:
# Passando um valor para função head podemos obter uma quantidade arbritrária de linhas
imoveis.head(10)

,ultimaAtualizacaoCadastral,situacao,sequencialImovel,proprietarioPrincipal,natureza,inscricaoImobiliaria,enderecoImovelNomeLogradouro,enderecoImovelMunicipio,enderecoImovelEstado,enderecoImovelComplemento,...,aliquotaImposto,situacaoPavimentacao,distrito,setor,quadra,face,lote,sequencial,longitude,latitude
0,02/12/2015,Ativo,1031171,MUNICIPIO DO RECIFE,Territorial,1.1410.190.02.0025.0000-6,RUA PAULINO GOMES DE SOUZA Q-PRACA,RECIFE,PE,NaN,...,0.0000,Parcialmente Pavimentado,1,1410,190,2,25,1031171,NaN,NaN
1,29/11/2015,Ativo,1032984,MUNICIPIO DO RECIFE,Territorial,1.1410.140.01.0730.0000-0,RUA DO FUTURO Q-AREA L-D,RECIFE,PE,NaN,...,0.0300,Parcialmente Pavimentado,1,1410,140,1,730,1032984,-34.904747,-8.036815
2,29/11/2015,Ativo,1049160,MUNICIPIO DO RECIFE,Predial,1.1426.030.01.0170.0000-3,RUA DR JOAQUIM ARRUDA FALCAO,RECIFE,PE,NaN,...,0.0000,Parcialmente Pavimentado,1,1426,30,1,170,1049160,-34.887555,-8.040748
3,29/11/2015,Ativo,1050834,MUNICIPIO DO RECIFE,Predial,1.1426.043.01.0379.0000-4,RUA SACADURA CABRAL,RECIFE,PE,NaN,...,0.0000,Não Pavimentado,1,1426,43,1,379,1050834,NaN,NaN
4,29/11/2015,Ativo,1063391,MUNICIPIO DO RECIFE,Territorial,1.1445.155.02.0670.0000-4,RUA CEL VIRGILIO DE MEDEIROS Q-A L-12,RECIFE,PE,NaN,...,0.0000,Parcialmente Pavimentado,1,1445,155,2,670,1063391,-34.876882,-8.044247
5,28/11/2015,Ativo,1063405,MUNICIPIO DO RECIFE,Predial,1.1445.155.02.0777.0000-9,RUA CEL VIRGILIO DE MEDEIROS,RECIFE,PE,NaN,...,0.0125,Não Pavimentado,1,1445,155,2,777,1063405,-34.876774,-8.044325
6,29/11/2015,Ativo,1065114,MUNICIPIO DO RECIFE,Predial,1.1445.183.03.0012.0000-7,AV CRUZ CABUGA,RECIFE,PE,NaN,...,0.0000,Pavimentado,1,1445,183,3,12,1065114,-34.876640,-8.046684
7,29/11/2015,Ativo,1070312,MUNICIPIO DO RECIFE,Territorial,1.1445.714.77.0001.0000-8,AV NORTE MIGUEL ARRAES DE ALENCAR,RECIFE,PE,NaN,...,0.0000,Parcialmente Pavimentado,1,1445,714,77,1,1070312,NaN,NaN
8,29/11/2015,Ativo,1081039,MUNICIPIO DO RECIFE,Predial,1.1450.140.04.0075.0000-4,AV CRUZ CABUGA,RECIFE,PE,NaN,...,0.0000,Pavimentado,1,1450,140,4,75,1081039,-34.876458,-8.047484
9,29/11/2015,Ativo,1087517,MUNICIPIO DO RECIFE,Predial,1.1450.290.02.0110.0000-8,RUA COELHO LEITE,RECIFE,PE,NaN,...,0.0000,Pavimentado,1,1450,290,2,110,1087517,-34.880778,-8.049867

In [45]:
# As últimas linhas "tail" as primeiras "head"
imoveis.tail(10)

,ultimaAtualizacaoCadastral,situacao,sequencialImovel,proprietarioPrincipal,natureza,inscricaoImobiliaria,enderecoImovelNomeLogradouro,enderecoImovelMunicipio,enderecoImovelEstado,enderecoImovelComplemento,...,aliquotaImposto,situacaoPavimentacao,distrito,setor,quadra,face,lote,sequencial,longitude,latitude
3085,29/11/2015,Ativo,7777353,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0314-1,RUA AMADOR BUENO,RECIFE,PE,APTO 301 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777353,-34.897103,-8.089021
3086,29/11/2015,Ativo,7777361,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0315-0,RUA AMADOR BUENO,RECIFE,PE,APTO 302 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777361,-34.897103,-8.089021
3087,29/11/2015,Ativo,7777370,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0316-8,RUA AMADOR BUENO,RECIFE,PE,APTO 303 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777370,-34.897103,-8.089021
3088,29/11/2015,Ativo,7777388,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0317-6,RUA AMADOR BUENO,RECIFE,PE,APTO 304 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777388,-34.897103,-8.089021
3089,29/11/2015,Ativo,7777396,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0318-4,RUA AMADOR BUENO,RECIFE,PE,APTO 305 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777396,-34.897103,-8.089021
3090,29/11/2015,Ativo,7777400,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0319-2,RUA AMADOR BUENO,RECIFE,PE,APTO 306 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777400,-34.897103,-8.089021
3091,29/11/2015,Ativo,7777418,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0320-6,RUA AMADOR BUENO,RECIFE,PE,APTO 307 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777418,-34.897103,-8.089021
3092,29/11/2015,Ativo,7777426,MUNICIPIO DO RECIFE,Predial,6.1710.069.02.0251.0321-4,RUA AMADOR BUENO,RECIFE,PE,APTO 308 BLOCO J,...,0.006,Pavimentado,6,1710,69,2,251,7777426,-34.897103,-8.089021
3093,29/11/2015,Ativo,7780141,MUNICIPIO DO RECIFE,Territorial,4.1540.067.01.0010.0001-5,RUA EDEIA,RECIFE,PE,NaN,...,0.000,Parcialmente Pavimentado,4,1540,67,1,10,7780141,NaN,NaN
3094,28/11/2015,Ativo,7780249,MUNICIPIO DO RECIFE,Predial,2.1185.015.10.0357.0001-6,RUA PORTAO DO GELO,RECIFE,PE,NaN,...,0.000,Não Pavimentado,2,1185,15,10,357,7780249,NaN,NaN

In [48]:
# Qual coluna contém mais elementos vazios
imoveis.isnull().sum().sort_values()

ultimaAtualizacaoCadastral         0
testadaFicticiaLote                0
superficieLote                     0
muradoLote                         0
aliquotaImposto                    0
                                ...
tipoEmpreendimentoMultipla      1555
anoConstrucaoMultipla           1555
quantidadePavimentosMultipla    1555
nomeEdificacaoMultipla          1579
nomeSuperContemMultipla         1654
Length: 63, dtype: int64

Salvar arquivo como excel

In [51]:
# primeiro voce cria o writer, aquele que escreve o arquivo. Passando como parametro o nome do arquivo
# e qual programa voce vai usar para gerar o arquivo.
# Para excel a engine é xlsxwriter
writer = pd.ExcelWriter("imoveis-alterado.xlsx", engine="xlsxwriter")
# depois disso, use o writer para converter as tabelas nesse arquivo
imoveis.to_excel(writer, sheet_name="imoveis")
# Por fim, chame a função save, para salvar o arquivo
writer.save()